title: Morski Klub Łączności "Szkuner" SP2ZIE
email: sp2zie@gmail.com
description: >-
  Klub SP2ZIE "Szkuner" to gdyński klub krótkofalarski związany z Uniwersytetem Morskim w Gdyni, 
  specjalizujący się w łącznościach satelitarnych i znany z przeprowadzenia pierwszej polskiej łączności 
  z astronautami na Międzynarodowej Stacji Kosmicznej w 2004 roku.
baseurl: ""
url: "https://www.sp2zie.pl"
github_username:  sp2zie
show_excerpts: true
date_format: "%Y-%m-%d"
