title: Morski Klub Łączności "Szkuner" SP2ZIE
description: >-
  Klub SP2ZIE "Szkuner" to gdyński klub krótkofalarski związany z Uniwersytetem Morskim w Gdyni, 
  specjalizujący się w łącznościach satelitarnych i znany z przeprowadzenia pierwszej polskiej łączności 
  z astronautami na Międzynarodowej Stacji Kosmicznej w 2004 roku.
baseurl: ""
url: "https://www.sp2zie.pl"
show_excerpts: true
date_format: "%Y-%m-%d"
facebook_url: https://www.facebook.com/profile.php?id=100063558938156
plugins:
  - jekyll-sitemap
